### ISSUE TITLE
Ideas for milestone 3

### ISSUE THREAD

**Issue by sukh2929** [UBC-MDS/labzen#34]

**Comment by sukh2929** [comment]
For function3, I will use username password authentication for easy testing and implementation of function3 and not use token to access Github.

**Comment by rtaph** [comment]
For the next round of development, it would be great to:

1. Make the credentials management more robust
2. Require less input from end users. Ideally, they should be able to run the functions with no arguments most of the time, from the directory of their assignment.
3. Add more sophisticated unit tests for `check_commits()` and `check_lat_version()`. These are hard to test because they require authentication, and/or are state dependent and require mocking.
4. Add unit test fixtures
5. Further test relative paths as function inputs. In particular, the `~` expansion for the home directory.
6. Check if a docopt version can be created to run this at the command line rather than in a python REPL.
7. Build the documentation
8. Improve the readme
9. Address failing builds in GHA.

**Comment by kmoravej** [comment]
- In Milestone 2, we were not able to test for user inputs. We should find a way to solve this issue. For example, In `parse_lab()`  function if the user did not provide a file path the function recursively search for all Jupyter Notebook and Rmarkdown file in the working directory and subdirectories. 
- The repo name and token to access the Github to check whether user made three commits or not.
-  Find a way to work with relative path to the notebook

**Comment by rtaph** [comment]
We ended up agreeing on the lab utilities package idea.
